defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "nnclr_400_cifar100_swin_2" # change here for cifar100
method: "nnclr"
warmm_epoch: 10
type: 'standard'
distance_thresh: .9
distance_min: .3
epoch_step: 100
step_type: 'step'
step_down: .1
beta: 1
tau_plus: 0.1

backbone:
  name: "swin_small"
  kwargs:
    img_size: 32
method_kwargs:
  decoder_embed_dim: 512
  decoder_depth: 8
  decoder_num_heads: 16
  temperature: 0.2
  proj_hidden_dim: 512
  pred_hidden_dim: 4096
  proj_output_dim: 256
  queue_size: 65536
data:
  dataset: cifar100 # change here for cifar100
  train_path: ""
  val_path: ""
  format: "image_folder"
  num_workers: 16
optimizer:
  name: "lars"
  batch_size: 256
  lr: 1.0
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: ""
  frequency: 1
  save_constant: True
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 400
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
