defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-imagenet-linear_10_percent"
pretrained_feature_extractor: ''
method: 'simclr'
backbone:
  name: "resnet50"
pretrain_method: "simclr"
data:
  dataset: imagenet
  train_path: ""
  val_path: ""
  format: "image_folder"
  fraction: 0.1
  num_workers: 32
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 1e-5
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: ""
  frequency: 1000
  save_constant: True
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
