defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr_imagenet_100_epochs_8"
method: 'simclr'
type: 'standard'
distance_thresh: .9
distance_min: .3
epoch_step: 20
step_type: 'step'
step_down: .1
beta: 1
tau_plus: 0.1
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  temperature: 0.1
data:
  dataset: imagenet
  train_path: ""
  val_path: ""
  format: "image_folder"
  num_workers: 32
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: ""
  frequency: 1
  save_constant: True
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
accumulate_grad_batches: 16
